anfisa_for_friends/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.description, name='description'),
]

anfisa_for_friends/anfisa_for_friends/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

urlpatterns = [
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),
    path('ice_cream/', include('ice_cream.urls')),
    path('admin/', admin.site.urls),

] 

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debug_toolbar:
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

anfisa_for_friends/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
]

anfisa_for_friends/ice_cream/urls.py
from django.urls import path

from . import views

app_name = 'ice_cream'

urlpatterns = [
    path('', views.ice_cream_list, name='ice_cream_list'),
    path('<int:pk>/', views.ice_cream_detail, name='ice_cream_detail'),
]

anfisa_for_friends/core/models.py
from django.db import models


class PublishedModel(models.Model):
    """Абстрактная модель. Добвляет флаг is_published."""
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    class Meta:
        abstract = True

anfisa_for_friends/homepage/models.py
from django.db import models


# Create your models here.

anfisa_for_friends/ice_cream/models.py
from django.db import models

from core.models import PublishedModel


class Category(PublishedModel):
    title = models.CharField(max_length=256, verbose_name='Название')
    slug = models.SlugField(max_length=64, unique=True, verbose_name='Слаг')
    output_order = models.PositiveSmallIntegerField(default=100, verbose_name='Название')

    class Meta():
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Topping(PublishedModel):
    title = models.CharField(max_length=256, verbose_name='Название')
    slug = models.SlugField(max_length=64, unique=True, verbose_name='Слаг')

    class Meta():
        verbose_name = 'топпинги'
        verbose_name_plural = 'Топпинги'

    def __str__(self):
        return self.title


class Wrapper(PublishedModel):
    title = models.CharField(max_length=256, verbose_name='Название', help_text='Уникальное название обёртки, не более 256 символов')

    class Meta():
        verbose_name = 'объект «Обёртка»'
        verbose_name_plural = 'Обёртки'

    def __str__(self):
        return self.title


class IceCream(PublishedModel):
    is_on_main = models.BooleanField(default=False, verbose_name='На главную')
    title = models.CharField(max_length=256, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    wrapper = models.OneToOneField(
        Wrapper,
        on_delete=models.SET_NULL,
        related_name='ice_cream',
        null=True,
        blank=True,
        verbose_name='Обёртка'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='ice_creams',
        verbose_name='Категории'
    )
    toppings = models.ManyToManyField(Topping)
    is_on_main = models.BooleanField(default=False, verbose_name='На главную')

    class Meta():
        verbose_name = 'мороженое'
        verbose_name_plural = 'Мороженое'

    def __str__(self):
        return self.title

anfisa_for_friends/about/views.py
from django.shortcuts import render


def description(request):
    template = 'about/description.html'
    return render(request, template)

anfisa_for_friends/homepage/views.py
from django.shortcuts import render
from ice_cream.models import IceCream


def index(request):
    template_name = 'homepage/index.html'

    ice_cream_list = IceCream.objects.values('id', 'title')

    context = {
        'ice_cream_list': ice_cream_list,
    }

    return render(request, template_name, context)

anfisa_for_friends/ice_cream/views.py
from django.shortcuts import render

def ice_cream_detail(request, pk):
    template = 'ice_cream/detail.html'
    context = {}
    return render(request, template, context)


def ice_cream_list(request):
    template = 'ice_cream/list.html'
    context = {}
    return render(request, template, context)


anfisa_for_friends/templates/about/description.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. О проекте
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">О проекте</h1>
  <p>
    Каталог экзотических сортов мороженого.
  </p>
{% endblock %}

anfisa_for_friends/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main class="pt-5 my-5">
      <div class="container">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
  <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

anfisa_for_friends/templates/homepage/index.html
{% extends "base.html" %}
{% block title %}
  Анфиса для друзей. Главная
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">Главная страница</h1>
  {% for ice_cream in ice_cream_list %}
    <h3>{{ ice_cream.title }}</h3>
    <p>ID: {{ ice_cream.id }}</p>
    <p>{{ ice_cream.description }}</p>
  {% endfor %}
{% endblock %}

anfisa_for_friends/templates/ice_cream/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Мороженое {{ ice_cream.name|lower }}
{% endblock %}
{% block content %}
  <h1 class="pb-2 mb-0">{{ ice_cream.name }}</h1>  
  <div class="row mt-3">
    <div class="col-12 col-md-6">
      <h2>Описание</h2>
      <p>{{ ice_cream.description }}</p>      
    </div> 
    <div class="col-12 col-md-6 mb-3">
      <img 
        class="img-fluid" 
        height="400" width="300"
        src="{% static 'img/image-holder.png' %}"
        >      
    </div>
  </div>     
{% endblock %}
 

anfisa_for_friends/templates/ice_cream/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Анфиса для друзей. Список мороженого
{% endblock %}
{% block content %}
<h1 class="pb-2 mb-0">Каталог мороженого</h1>
  <div class="row">
    {% for ice_cream in ice_cream_list %}
      <div class="col-6 col-md-4 my-1">
        <div class="card">
          <img 
            class="img-fluid card-img-top" 
            height="400" width="300"
            src="{% static 'img/image-holder.png' %}"
          >
          <div class="card-body">           
            <h5 class="card-title">{{ ice_cream.name }}</h5>
            <p class="card-text">{{ ice_cream.description|truncatewords:10 }}</p>
            <a class="mt-3 regular-link" href="{% url 'ice_cream:ice_cream_detail' ice_cream.id %}">
              Подробнее -->           
            </a>
          </div>
        </div>
      </div>   
    {% endfor %}
  </div>
{% endblock %}

anfisa_for_friends/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© «MyKit Corp»</p>
</footer> 

anfisa_for_friends/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <div 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        {% with request.resolver_match.view_name as view_name %}            
        <ul class="nav nav-pills">
          <li class="nav-item">              
            <a
              class="nav-link {% if view_name == 'homepage:index' %} active {% endif %}" 
              href="{% url 'homepage:index' %}"
              >
              Главная 
            </a> 
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name == 'ice_cream:ice_cream_list' %} active {% endif %}" 
              href="{% url 'ice_cream:ice_cream_list' %}"
              >
              Каталог мороженого
            </a> 
          </li>
          <li class="nav-item">
            <a 
              class="nav-link {% if view_name == 'about:description' %} active {% endif %}"
              href="{% url 'about:description' %}"
            >
              О проекте
            </a> 
          </li>
        </ul>
        {% endwith %}
      </div> 
      <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'img/logo.png' %}" height="50" class="d-inline-block align-top" alt="">            
      </a>         
    </div>
  </nav>
</header>